[pt_table]
#partition table is 4K in size
address0 = 0xE000
address1 = 0xF000
# If version is 2, It will use dynamic mode.
version = 2

[[pt_entry]]
type = 16
name = "Boot2"
device = 0
address0 = 0
size0 = 0xE000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
# If header is 1, it will add the header.
header = 1
# If header is 1 and security is 1, It will be encrypted.
security = 1

[[pt_entry]]
type = 0
name = "FW"
device = 0
address0 = 0x10000
size0 = 0x200000
address1 = 0x210000
size1 = 0x200000
# compressed image must set len,normal image can left it to 0
len = 0
# If header is 1, it will add the header.
header = 1
# If header is 1 and security is 1, It will be encrypted.
security = 1

[[pt_entry]]
type = 10
name = "mfg"
device = 0
address0 = 0x210000
size0 = 0x60000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
# If header is 1, it will add the header.
header = 1
# If header is 1 and security is 1, It will be encrypted.
security = 1

[[pt_entry]]
type = 4
name = "kv"
device = 0
address0 = 0x410000
size0 = 0x10000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
# If header is 1, it will add the header.
header = 0
# If header is 1 and security is 1, It will be encrypted.
security = 0

[[pt_entry]]
type = 5
name = "media"
device = 0
address0 = 0x420000
size0 = 0x80000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
# If header is 1, it will add the header.
header = 0
# If header is 1 and security is 1, It will be encrypted.
security = 0

[[pt_entry]]
type = 8
# It shows Dts in DevCube 
name = "factory"
device = 0
address0 = 0x4A0000
size0 = 0x6000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
# If header is 1, it will add the header.
header = 0
# If header is 1 and security is 1, It will be encrypted.
security = 0

[[pt_entry]]
type = 9
name = "Imgload"
device = 0
address0 = 0x500000
size0 = 0x80000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0x3efa0001
# If header is 1, it will add the header.
header = 1
# If header is 1 and security is 1, It will be encrypted.
security = 1

[[pt_entry]]
type = 10
name = "SBI"
device = 0
address0 = 0x580000
size0 = 0x40000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0x3ef8000F
# If header is 1, it will add the header.
header = 1
# If header is 1 and security is 1, It will be encrypted.
security = 1

[[pt_entry]]
type = 11
name = "DTB"
device = 0
address0 = 0x5C0000
size0 = 0x8000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0x3f00000F
# If header is 1, it will add the header.
header = 1
# If header is 1 and security is 1, It will be encrypted.
security = 1

[[pt_entry]]
type = 12
name = "Kernel"
device = 0
address0 = 0x600000
size0 = 0x700000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0x5100000F
# If header is 1, it will add the header.
header = 1
# If header is 1 and security is 1, It will be encrypted.
security = 1

[[pt_entry]]
type = 13
name = "Rootfs"
device = 0
address0 = 0xD00000
size0 = 0x300000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0x5200000F
# If header is 1, it will add the header.
header = 1
# If header is 1 and security is 1, It will be encrypted.
security = 1
