[pt_table]
#partition table is 4K in size
address0 = 0xE000
address1 = 0xF000

[[pt_entry]]
type = 0
name = "FW_CPU0"
device = 0
address0 = 0x60000
size0 = 0x64000
address1 = 0xC4000
size1 = 0x32000
# compressed image must set len,normal image can left it to 0
len = 0

[[pt_entry]]
type = 10
name = "PSM"
device = 0
address0 = 0xF6000
size0 = 0x2000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0

[[pt_entry]]
type = 2
name = "factory"
device = 0
address0 = 0xF8000
size0 = 0x8000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0

